name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hi Pradeepta"
      - name: Print GoodBye
        run: echo "Done - bye"
